version: '3.8'

services:
  moneytime-app:
    image: altusrossouw/moneytime-app:latest
    container_name: moneytime-app
    restart: unless-stopped
    ports:
      - "3330:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NEXT_TELEMETRY_DISABLED=1
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.moneytime.rule=Host(`yourdomain.com`)"
      - "traefik.http.routers.moneytime.entrypoints=websecure"
      - "traefik.http.routers.moneytime.tls.certresolver=letsencrypt"
      - "traefik.http.services.moneytime.loadbalancer.server.port=3000"